# Generated by Django 3.2.5 on 2021-07-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
