# Generated by Django 3.2.5 on 2021-07-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_guitar_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InherTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.CharField(max_length=50)),
                ('some_info', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
