# Generated by Django 3.2.5 on 2021-07-14 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_inhertest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InherTest',
        ),
    ]
