# Generated by Django 3.2.5 on 2021-07-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_delete_inhertest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guitar',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='guitar',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='guitar',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='guitar',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='guitar',
            name='production_year',
        ),
        migrations.RemoveField(
            model_name='guitar',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='piano',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='piano',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='piano',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='piano',
            name='production_year',
        ),
        migrations.RemoveField(
            model_name='piano',
            name='segment',
        ),
    ]
