# Generated by Django 3.2.5 on 2021-07-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210714_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='in_stock',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='guitar',
            name='model_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='guitar',
            name='production_year',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guitar',
            name='segment',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='piano',
            name='in_stock',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='piano',
            name='model_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='piano',
            name='production_year',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='piano',
            name='segment',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
