# Generated by Django 3.2.5 on 2021-07-15 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210714_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=40, null=True)),
                ('production_year', models.CharField(max_length=20, null=True)),
                ('segment', models.CharField(max_length=40, null=True)),
                ('description', models.TextField()),
                ('features', models.TextField()),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('instrument_type', models.CharField(max_length=50)),
                ('in_stock', models.BooleanField(default=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument', to='store.brand')),
            ],
        ),
        migrations.DeleteModel(
            name='Guitar',
        ),
        migrations.DeleteModel(
            name='Piano',
        ),
    ]
