# Generated by Django 3.2.5 on 2021-07-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210715_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
