# Generated by Django 3.2.5 on 2021-07-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_instrument_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
    ]
